gimnasio/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('members/', include('members.urls')),
    path('', user_views.home, name='home'),
]

members/urls.py
from django.urls import path
from . import views
from .views import get_tclass_info, obtener_precio_grupo, InscripcionUpdateView, InscripcionUpdateV,pagos_todos
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('register_member/', views.register_member, name='register_member'),
    path('update_member/', views.update_member, name='update_member'),
    path('update_member_admin/<int:id>/', views.update_member_admin, name='update_member_admin'),
    path('delete_member/<int:id>/', views.delete_member, name='delete_member'),
    path('list_members/', views.list_members, name='list_members'),
    
    path('list_instructors/', views.list_instructors, name='list_instructors'),
    path('create_instructor/', views.create_instructor , name='create_instructor'),
    path('update_instructor/<int:id>/', views.update_instructor, name='update_instructor'),

    path('calendar_instructor/', views.calendar_view, name='calendar_inst'),
    path('instructor_schedule/', views.instructor_schedule_view, name='instructor_schedule'),

    path('list_classes/', views.list_classes, name='list_classes'),
    path('create_class/', views.create_class , name='create_class'),
    path('update_class/<int:id>/', views.update_class, name='update_class'),

    path('list_groups/', views.list_group, name='list_groups'),
    path('create_group/', views.create_group , name='create_group'),
    path('update_group/<int:id>/', views.update_group, name='update_group'),
    path('get_tclass_info/', get_tclass_info, name='get_tclass_info'),
    path('obtener_precio_grupo/', obtener_precio_grupo, name='obtener_precio_grupo'),

    path('list_inscribes/', views.list_inscribe, name='list_inscribes'),
    path('create_inscription/', views.inscription_create, name='create_inscription'),

    path('update_inscription/<int:id>/', views.update_class, name='update_class'),

    path('inscripcion/<int:pk>/editar/', InscripcionUpdateView.as_view(), name='inscripcion_edit'),

    path('register_pay/', views.register_pay, name='register_pay'),
    path('inscripcionV/<int:pk>/editar/', InscripcionUpdateV.as_view(), name='inscripcion_editar'),

    path('pagos/', views.pagos_registrados_view, name='lista-pagos'),
    path('pagos/todos', views.pagos_todos , name='lista-pagos-todos'),
    path('pagos/validar/<int:pago_id>/', views.validar_pago, name='validar-pago'),
    path('pagos/invalidar/<int:pago_id>/', views.invalidar_pago, name='invalidar-pago'),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('home/', views.home, name='home'),
]

members/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django import forms


class Member(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    nombre = models.CharField("Nombre", max_length=60, blank=False, null=False)
    ap_pat = models.CharField("Apellido Paterno", max_length=60, blank=False, null=False)
    ap_mat = models.CharField("Apellido Materno", max_length=60)
    GENERO_CHOICES = [
        ('H', 'Hombre'),
        ('M', 'Mujer'),
    ]
    genero = models.CharField("Género", max_length=1, choices=GENERO_CHOICES, blank=False, null=False)
    fec_nac = models.DateField("Fecha de Nacimiento", blank=False, null=False)
    telefono = models.CharField("Teléfono", max_length=12, blank=False, null=False)
    email = models.EmailField("Correo Electrónico", unique=True, blank=False, null=False)
    direccion = models.CharField("Direccion", max_length=250)
    fec_reg = models.DateTimeField("Fecha de Registro", default=timezone.now, blank=False, null=False)
    estatus = models.BooleanField("Estatus", default=True, blank=False, null=False)

    pagos_real = models.DecimalField("Pagos Realizados",
        max_digits=9,  # 7 enteros + 2 decimales = 9 dígitos en total
        decimal_places=2,  # Especifica 2 decimales
        default=0.00  # Valor por defecto (opcional)
    )
    pagos_validado = models.DecimalField("Pagos Validados",
        max_digits=9,  # 7 enteros + 2 decimales = 9 dígitos en total
        decimal_places=2,  # Especifica 2 decimales
        default=0.00  # Valor por defecto (opcional)
    )
    pagos_usados = models.DecimalField("Pagos Usados",
        max_digits=9,  # 7 enteros + 2 decimales = 9 dígitos en total
        decimal_places=2,  # Especifica 2 decimales
        default=0.00  # Valor por defecto (opcional)
    )
    saldo = models.DecimalField("Saldos ",
        max_digits=9,  # 7 enteros + 2 decimales = 9 dígitos en total
        decimal_places=2,  # Especifica 2 decimales
        default=0.00  # Valor por defecto (opcional)
    )


    def __str__(self):
        return f"{self.nombre} {self.ap_pat} {self.ap_mat}"

class Instructor(models.Model):
    nombre = models.CharField("Nombre Completo", max_length=120, blank=False,  null=False)
    fec_nac = models.DateField("Fecha de Nacimiento", blank=False, null=False)
    telefono = models.CharField("Teléfono", max_length=12, blank=False, null=False)
    estudios = models.CharField("Estudios", max_length=100, blank=True, null=True)
    certificacion = models.CharField("Estudios", max_length=100, blank=True, null=True)
    GENERO_CHOICES = [
        ('H', 'Hombre'), 
        ('M', 'Mujer'),
    ]
    genero = models.CharField("Género", max_length=1, choices=GENERO_CHOICES, blank=False, null=False)
    email = models.EmailField("Correo Electrónico", blank=False, null=False)
    direccion = models.CharField("Direccion", max_length=250)
    fec_reg = models.DateTimeField("Fecha de Registro", default=timezone.now, blank=False, null=False)
    estatus = models.BooleanField("Estatus", default=True, blank=False, null=False)
    def __str__(self):
        return f"{self.nombre} "

class Tclass(models.Model):
    describe = models.CharField("Curso ", max_length=80,blank=False, null=False)
    duracion = models.IntegerField("Tiempo(min)")
    requisitos = models.CharField("Requisitos",max_length=120, blank=True, null=True)
    observa = models.CharField("Observaciones",max_length=300, blank=True, null=False)
    minimo = models.IntegerField("Minimo integrantes", default=1)
    maximo = models.IntegerField("Maximo integrantes", default=10)
    fec_reg = models.DateTimeField("Fecha de Registro", default=timezone.now, blank=False, null=False)
    estatus = models.BooleanField("Estatus", default=True, blank=False, null=False)
    creo = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return f"{self.describe} "

class Grupo(models.Model):
    grupo = models.CharField("Grupo", max_length=80, blank=False, null=False)
    clase = models.ForeignKey(Tclass, on_delete=models.CASCADE, blank=False, null=False)
    instructor = models.ForeignKey(Instructor, on_delete=models.CASCADE)
    observa = models.CharField("Observaciones",max_length=300, blank=True, null=False)
    MODALIDAD_CHOICES = [
        ('P', 'Presencial'),
        ('R', 'Remoto'),
        ('H', 'Hibrido'),
    ]
    modalidad = models.CharField("Modalidad", max_length=1, choices=MODALIDAD_CHOICES, blank=False, null=False)
    costo = models.DecimalField("Costo Curso",
        max_digits=9,  # 7 enteros + 2 decimales = 9 dígitos en total
        decimal_places=2,  # Especifica 2 decimales
        default=1.00  # Valor por defecto (opcional)
    )
    preciounitario = models.DecimalField("Precio x Persona",
        max_digits=9,  # 7 enteros + 2 decimales = 9 dígitos en total
        decimal_places=2,  # Especifica 2 decimales
        default=1.00  # Valor por defecto (opcional)
    )
    minimo = models.IntegerField("Minimo integrantes", default=1)
    maximo = models.IntegerField("Maximo integrantes", default=10)
    duracion = models.IntegerField("Tiempo(min)")
    horaInicio = models.TimeField("Hora Inicial")  # Utiliza TimeField para almacenar la hora
    horaTermino = models.TimeField("Hora Termina")  # Utiliza TimeField para almacenar la hora

    fec_reg = models.DateTimeField("Fecha de Registro", default=timezone.now, blank=False, null=False)
    estatus = models.BooleanField("Estatus", default=True, blank=False, null=False)
    creo = models.ForeignKey(User, on_delete=models.CASCADE, blank=False, null=False)
    dias_semana = models.JSONField("Días de la semana", default=dict, blank=False, null=False )

    fec_ini = models.DateField("Fecha de Inicio", blank=True, null=True)  # Nuevo campo
    fec_fin = models.DateField("Fecha de Fin", blank=True, null=True)  # Nuevo campo

    def __str__(self):
        return f"{self.grupo} - {self.instructor}"

class Inscripcion(models.Model):
    member   = models.ForeignKey(Member, on_delete=models.CASCADE, blank=False, null=False)
    grupo    = models.ForeignKey(Grupo, on_delete=models.CASCADE, blank=False, null=False)
    cantidad = models.IntegerField("Cantidad", default=1, blank=False, null=False)
    preciounitario = models.DecimalField("Precio Unitario",
        max_digits=9,  # 7 enteros + 2 decimales = 9 dígitos en total
        decimal_places=2,  # Especifica 2 decimales
        default=1.00  # Valor por defecto (opcional)
    )
    preciototal = models.DecimalField("Precio Total",
        max_digits=9,  # 7 enteros + 2 decimales = 9 dígitos en total
        decimal_places=2,  # Especifica 2 decimales
        default=1.00  # Valor por defecto (opcional)
    )
    descuento = models.DecimalField("Descuento", 
        max_digits=9,  # 7 enteros + 2 decimales = 9 dígitos en total
        decimal_places=2,  # Especifica 2 decimales
        default=0.00  # Valor por defecto (opcional)
    )
    pagado = models.DecimalField("Pagado", 
        max_digits=9,  # 7 enteros + 2 decimales = 9 dígitos en total
        decimal_places=2,  # Especifica 2 decimales
        default=0.00  # Valor por defecto (opcional)
    )
    fec_reg = models.DateTimeField("Fecha de Registro", default=timezone.now, blank=False, null=False)
    estado_CHOICES = [
        ('S', 'Solicitado'),
        ('E', 'En proceso'),
        ('P', 'Pagado'),
        ('A', 'Autorizado'),
        ('N', 'No Autorizado'),
        ('C', 'Cancelado'),
        ('V', 'Vigente'),
        ('T', 'Tomado')
    ]
    estado = models.CharField("Estado", max_length=1, choices=estado_CHOICES, default='S', blank=False, null=False)
    fec_ini = models.DateField("Fecha Inicio", default=timezone.now, blank=True, null=True)
    fec_fin = models.DateField("Fecha Termino", blank=True, null=True)
    comprobante = models.CharField("Comprobante", max_length=60, blank=True, null=True)
    foto_comp =models.CharField("Foto", max_length=200, blank=True, null=True)
    fec_reg = models.DateTimeField("Fecha de Registro", default=timezone.now, blank=False, null=False)
    estatus = models.BooleanField("Estatus", default=True, blank=False, null=False)
    creo = models.ForeignKey(User, on_delete=models.CASCADE, blank=False, null=False)

    def __str__(self):
        return f"{self.member} - {self.grupo}"

class UpdateInscription(forms.ModelForm):
    class Meta:
        model = Inscripcion
        fields = [
            'member', 'grupo', 'cantidad', 'preciounitario', 'preciototal',
            'descuento', 'pagado', 'estado', 'fec_ini', 'fec_fin',
            'comprobante', 'foto_comp', 'estatus'
        ]

class Pago(models.Model):
    member   = models.ForeignKey(Member, on_delete=models.CASCADE, blank=False, null=False)
    describe = models.CharField("Describe ", max_length=80,blank=False, null=False)
    fecha_pago = models.DateTimeField("Fecha de Pago", default=timezone.now, blank=False, null=False)
    pago = models.DecimalField("Pagado", 
        max_digits=9,  # 7 enteros + 2 decimales = 9 dígitos en total
        decimal_places=2,  # Especifica 2 decimales
        default=0.00  # Valor por defecto (opcional)
    )
    RFC = models.CharField("RFC ", max_length=15,blank=False, null=False)
    documento = models.FileField("Documento", upload_to='documentos_pagos/', blank=False, null=False)
    ESTATUS_CHOICES = [
        ('R', 'Registro'),
        ('N', 'Sin Validez'), 
        ('V', 'Validado'),
    ]
    genero = models.CharField("Estatus", max_length=1, choices=ESTATUS_CHOICES, default = 'R', blank=False, null=False)
    fec_reg = models.DateTimeField("Fecha de Registro", default=timezone.now, blank=False, null=False)

    def __str__(self):
        return f"{self.describe} "

members/templates/members/create_class.html
{% extends 'base.html' %}

{% block title %}Registra Clases{% endblock %}

{% block content %}
{% load crispy_forms_tags %}

<h2>Registro de las Clases a Impartir</h2>
<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit">Registrar</button>
</form>

{% endblock %}

members/templates/members/create_inscription.html
{% extends 'base.html' %}

{% block title %}Inscripcion{% endblock %}

{% block content %}
{% load crispy_forms_tags %}

    <h2>Inscripcion a grupo</h2>

    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Registrar</button>
    </form>

{% endblock %}

members/templates/members/create_instructor.html
{% extends 'base.html' %}

{% block title %}Registra Instructor{% endblock %}

{% block content %}
{% load crispy_forms_tags %}

<h2>Registro de los Instructores</h2>
<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit">Registrar</button>
</form>

{% endblock %}

members/templates/members/instructor_schedule.html
{% extends 'base.html' %}

{% block title %}Horario Instructor{% endblock %}

{% block content %}
{% load crispy_forms_tags %}

<form method="POST">
    {% csrf_token %}
    <table style="width: 80%;">
        <tr>
            <th style="text-align: left;">    {{ form|crispy }}</th>
            <th style="text-align: right;"> <button type="submit">Ver Horario</button> </th>
        </tr>
    </table>
</form>

{% if schedule %}
    <table border="1" style="width: 80%; margin: auto; text-align: center;">
        <thead>
            <tr>
                <th>Hora</th>
                <th>Lunes</th>
                <th>Martes</th>
                <th>Miércoles</th>
                <th>Jueves</th>
                <th>Viernes</th>
                <th>Sábado</th>
                <th>Domingo</th>
            </tr>
        </thead>
        <tbody>
            {% for hour, days in schedule.items %}
                <tr>
                    <td>{{ hour }}:00 --> </td>
                    {% for day, course in days.items %}
                        <td class="{% if not class.estatus %}azul{% endif %}">{{ course }}</td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endif %}
{% endblock %}

members/templates/members/list_inscribe.html
{% extends 'base.html' %}

{% block title %}Lista Inscripciones{% endblock %}

{% block content %}

<h2>Listado de las Inscripciones en el Sistema</h2>

<table class="styled-table">
    <thead>
        <tr>
            <th>Miembro</th>
            <th>Grupo</th>
            <th>Estado</th>
            <th>Fecha Inicial</th>
            <th>Fecha Final</th>
            <th>Cantidad</th>
            <th>Precio Total</th>
            <th>Pago Total </th>
            <th>Saldo Disponible</th>
            <th>Activo</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for inscribe in inscribes %}
        <tr>
            <td>{{ inscribe.id}} - {{ inscribe.member }}</td>
            <td>{{ inscribe.grupo }}</td>
            <td>{{ inscribe.get_estado_display }}</td>
            <td>{{ inscribe.fec_ini }}</td>
            <td>{{ inscribe.fec_fin }}</td>
            <td>{{ inscribe.cantidad }}</td>
            <td>${{ inscribe.preciototal }}</td>
            <td>${{ inscribe.pagado }}</td>
            <td>{{ inscribe.member.saldo }}</td>
            <td class="{% if not inscribe.estatus %}rojo{% endif %}" >
                {% if inscribe.estatus %}
                Sí
                {% else %}
                No
                {% endif %}
            </td>
            <td>
                <a href="{% url 'inscripcion_editar' inscribe.id %}" class="btn btn-update">Actualiza</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<a href="{% url 'create_inscription' %}" class="{% if request.resolver_match.url_name == 'create_inscription' %}active{% endif %}">
    <button type="submit" class="boton-negro">
       Nueva Inscripción
    </button>
  </a>


{% endblock %}

          
           
       
         
         

members/templates/members/list_instructor.html
{% extends 'base.html' %}

{% block title %}Lista Instructores{% endblock %}

{% block content %}

<h2>Listado de Instructores</h2>

<table class="styled-table">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Fec Nac.</th>
            <th>Telefono</th>
            <th>Estudios</th>
            <th>Certificacion</th>
            <th>Genero</th>
            <th>Email</th>
            <th>Direccion</th>
            <th>Activo</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for instructor in instructors %}
        <tr>
            <td class="{% if not instructor.estatus %}rojo{% endif %}">{{ instructor.nombre }}</td>
            <td>{{ instructor.fec_nac }}</td>
            <td>{{ instructor.telefono }}</td>
            <td>{{ instructor.estudios }}</td>
            <td>{{ instructor.certificacion }}</td>
            <td>{{ instructor.get_genero_display }}</td>
            <td>{{ instructor.email }}</td>
            <td>{{ instructor.direccion }}</td>
            <td class="{% if not instructor.estatus %}rojo{% endif %}" >
                {% if instructor.estatus %}
                Sí
                {% else %}
                No
                {% endif %}
            </td>
            <td>
                <a href="{% url 'update_instructor' instructor.id %}" class="btn btn-update">Actualiza</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<a href="{% url 'create_instructor' %}" class="{% if request.resolver_match.url_name == 'create_instructor' %}active{% endif %}">
    <button type="submit" class="boton-negro">
       Nuevo Instructor
    </button>
  </a>
{% endblock %}

        
   
          
           
       
         
         

members/templates/members/list_members.html
{% extends 'base.html' %}

{% block title %}Lista Miembros{% endblock %}

{% block content %}
<h2>Listado de Miembros</h2>
<table class="styled-table">
    <thead>
        <tr>
            <th>Usuario</th>
            <th>Nombre Completo</th>
            <th>Género</th>
            <th>Fec. Nac.</th>
            <th>Teléfono</th>
            <th>Email</th>

            <th>Pagos Registrados</th>
            <th>Pagos Validados</th>
            <th>Pagos Utililizados</th>
            <th>Saldos Disponible </th>
            
            <th>Dirección</th>
            <th>Activo</th>
            <th>Fec. Reg.</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for member in members %}
        <tr>
            <td class="{% if not member.estatus %}rojo{% endif %}">{{ member.user }}</td>
            <td>{{ member.nombre }} {{ member.ap_pat }} {{ member.ap_mat }}</td>
            <td>{{ member.get_genero_display }}</td>
            <td>{{ member.fec_nac }}</td>
            <td>{{ member.telefono }}</td>
            <td>{{ member.email }}</td>

            <td>$ {{ member.pagos_real }}</td>
            <td>$ {{ member.pagos_validado }}</td>
            <td>$ {{ member.pagos_usados }}</td>
            <td>$ {{ member.saldo }}</td>

            
            <td>{{ member.direccion }}</td>
            <td class="{% if not member.estatus %}rojo{% endif %}">
                    {% if member.estatus %}
                    Sí
                    {% else %}
                    No
                    {% endif %}

            </td>
            <td>{{ member.fec_reg }}</td>
            <td>
                <a href="{% url 'update_member_admin' member.id %}" class="btn btn-update">Actualiza</a>
                <a href="{% url 'delete_member' member.id %}" class="btn btn-delete" onclick="return confirm('Are you sure you want to delete this member?');">Borrar</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

<td {% if not instructor.activo %}style="color: red;"{% endif %}>
    {% if instructor.activo %}
    Sí
    {% else %}
    No
    {% endif %}

members/templates/members/lista_pagos_todos.html
{% extends 'base.html' %}

{% block title %}Validación Pagos{% endblock %}

{% block content %}

<h2>Listado de Pagos de los Miembros </h2>

<table class="styled-table">
    <thead>
        <tr>
            <th>Miembro</th>
            <th>Descripción</th>
            <th>Fecha de Pago</th>
            <th>Monto</th>
            <th>RFC</th>
            <th>Documento</th>
            <th>Estatus</th>
            <th>Fec. Registro</th>
        </tr>
    </thead>
    <tbody>
        {% for pago in pagos %}
        <tr>
            <td>{{ pago.member }}</td>
            <td>{{ pago.describe }}</td>
            <td>{{ pago.fecha_pago }}</td>
            <td>$ {{ pago.pago }}</td>
            <td>{{ pago.RFC }}</td>
            <td><a href="{{ pago.documento.url }}" target="_blank">Ver Documento</a></td>
            </td>
            <td>{{ pago.get_genero_display }}</td>
            <td>{{ pago.fec_reg }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

  {% endblock %}

members/templates/members/register_member.html
{% extends 'base.html' %}

{% block title %}Registro Miembro{% endblock %}

{% block content %}
<h2>Registro como Miembro</h2>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Registrar</button>
</form>
{% if form.errors %}
    <div class="errors">
        <ul>
            {% for field in form %}
                {% for error in field.errors %}
                    <li>{{ field.label }}: {{ error }}</li>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    </div>
{% endif %}
{% endblock %}

members/templates/members/register_pay.html
{% extends 'base_cel.html' %}

{% block title %}Registra Pagos{% endblock %}

{% block content %}
{% load crispy_forms_tags %}

<h2>Registro Pagos de los Miembros</h2>

    <table class="styled-table">
        <thead>
            <tr> 
                <th>Descripcion </th>
                <th>Fecha Pago</th>
                <th>Importe Pago</th>
                <th>RFC</th>
                <th>Estatus</th>
            </tr>
        </thead>
        <tbody>
            {% for pago in pagos %}
            <tr>
                <td>{{ pago.describe }}</td>
                <td>{{ pago.fecha_pago }}</td>
                <td>${{ pago.pago }}</td>
                <td>{{ pago.rfc }}</td>
                <td>{{ pago.get_genero_display }}</td>
            {% endfor %}
        </tbody>
    </table>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {{ form|crispy }}
    <button type="submit">Registrar Pago</button>
</form>


{% endblock %}

members/templates/members/update_class.html
{% extends 'base.html' %}

{% block title %}Actualiza Clase{% endblock %}

{% block content %}
{% load crispy_forms_tags %}

<h2>Actualiza los datos de las clases</h2>
<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit">Actualizar </button>
    <a href="{% url 'list_classes' %}" class="btn btn-cancel">Cancelar</a>
</form>

{% endblock %}

members/templates/members/update_group.html
{% extends 'base.html' %}

{% block title %}Actualiza Grupos{% endblock %}

{% block content %}
{% load crispy_forms_tags %}

<h2>Actualizacion de Grupos</h2>
<form method="POST">
    {% csrf_token %}

    {{ form|crispy }}

    <button type="submit">Actualizar </button>
    <a href="{% url 'list_groups' %}" class="btn btn-cancel">Cancelar</a>
</form>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        const dateField = document.querySelector('input[name="fec_nac"]');
        const dateValue = '{{ member.fec_nac|date:"Y-m-d" }}';
        if (dateField && dateValue) {
            dateField.value = dateValue;
        }
    });
</script>

{% endblock %}

members/templates/members/update_member.html
{% extends 'base_cel.html' %}
{% block title %}Actualiza Miembro{% endblock %}

{% block content %}
<div class="container form-container">
    <h2>Actualizacion Datos Miembro</h2>

    {% load crispy_forms_tags %}
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Actualizar</button>
        <a href="{% url 'home' %}" class="btn btn-secondary">Cancelar</a>
    </form>
    {% if form.errors %}
        <div class="errors">
            <ul>
                {% for field in form %}
                    {% for error in field.errors %}
                        <li>{{ field.label }}: {{ error }}</li>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
</div>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        const dateField = document.querySelector('input[name="fec_nac"]');
        const dateValue = '{{ member.fec_nac|date:"Y-m-d" }}';
        if (dateField && dateValue) {
            dateField.value = dateValue;
        }
    });

    const telefonoInput = document.getElementById('telefono');
    telefonoInput.addEventListener('input', function (e) {
        const inputValue = e.target.value.replace(/\D/g, ''); // Elimina caracteres no numéricos
        let formattedValue = '';

        if (inputValue.length > 0) {
            formattedValue += inputValue.slice(0, 2);
            if (inputValue.length > 2) {
                formattedValue += '-' + inputValue.slice(2, 6);
            }
            if (inputValue.length > 6) {
                formattedValue += '-' + inputValue.slice(6, 10);
            }
        }

        e.target.value = formattedValue;
    });
</script>
{% endblock %}

members/templates/members/update_member_admin.html
{% extends 'base.html' %}

{% block title %}Actualiza Miembro{% endblock %}

{% block content %}
{% load crispy_forms_tags %}

<h2>Actualiza Miembro</h2>

<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit">Actualizar </button>
    <a href="{% url 'list_members' %}" class="btn btn-cancel">Cancelar</a>
</form>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        const dateField = document.querySelector('input[name="fec_nac"]');
        const dateValue = '{{ member.fec_nac|date:"Y-m-d" }}';
        if (dateField && dateValue) {
            dateField.value = dateValue;
        }
    });
</script>

{% endblock %}